### ISSUE TITLE
User scripts and third-party scripts

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#1]
Here's a proposal for dealing with both user scripts and scripts install from another source:
- The user can write his/her own scripts in the .racket/quickscript/user-scripts directory.
- When installing a package containing scripts, a call to `register-script-directory` of `quickscript/library` is made and quickscript writes this in a file so as to know where to look for third-party scripts. These scripts are automatically updated if the corresponding package is updated. That allows for creating several packages of scripts that will all be used.
- The user can still import third-party scripts into the local user-scripts directory, but in that case they can't be updated with the corresponding package.

How does this sound?

**Comment by Metaxal** [comment]
I found a way to give the user the possibility to change the default properties of a script while ensuring that the script remains in its package and can be updated. I currently call that "shadow scripts", because they shadow the original script('s properties).

Instead of important the entire script, the user can create a new local script 
```
#lang racket/base
(require quickscript/script
         quickscript-extra/scripts/def-signatures) ; where the original script is defined

;; Define a new script that only changes the properties of the original script
(define-script my-def-signatures
  #:label "Def signatures"
  #:shortcut f8
  #:shortcut-prefix (ctl)
  ; then simply call the original script's procedure
  def-signatures)
```

Some facilities to make this process as painless as possible should be provided to the user.

**Comment by spdegabrielle** [comment]
I think these are both good.

With the 'shadow scripts' won't the original script still be present?
Would you have two entries in the scripts menu?
- the original menu item for 'def-signatures'
- the new menu item for 'my-def-signatures' 
...or does the use of the same #:label stop the old 'def-signatures' from being in the menus?

PS: A mechanism to turn off specific scripts seems like a desirable by product of this.

**Comment by Metaxal** [comment]
My thoughts exactly.

I'm thinking of adding a `other-scripts.rktd` file in the user-scripts directory, which contains a list of directories to search for scripts. The keyword `except-in` can be used to exclude scripts in a given directory (just like the same keyword for Racket's `require`). 

When installing the quickscript-extra package, the user must do:
```
$ raco pkg install quickscript-extra
$ racket -l quickscript-extra/install
```
The last line can also be done inside DrRacket with just `(require quickscript-extra/install)`.

This last call updates the file `other-scripts.rktd` to include quickscript-extra's directory.

Removing scripts is feasible with this, but isn't yet very user-friendly though.

**Comment by Metaxal** [comment]
All done in the new commits.

`quickscript` and `quickscript-extra` are now ready to use!

Remove the script plugin first if you have it.

First install `quickscript` as per the [readme](https://github.com/Metaxal/quickscript). It comes without any script.
Then follow `quickscript-extra`'s [readme](https://github.com/Metaxal/quickscript-extra) to install the additional scripts.

There is a new library system (accessible in `Scripts>Manage scripts>Library`) where directories containing scripts can be added, and specific scripts can be excluded.

I'm quite happy with the result :) Thanks a lot for your help and comments!

**Comment by Metaxal** [comment]
Now with shadow scripts!

**Comment by spdegabrielle** [comment]
It’s been a pleasure. I’ll update tonight and have a go.

What do you think about a ‘request for beta testers’ announcement on the Racket users list, Slack and IRC?

**Comment by Metaxal** [comment]
That's a good idea. Hold off for now though, as I'm still making some changes. I'll probably adjust it as I use it myself, then in a week or two we can ask for beta testers.

I'm closing this issue. Please don't hesitate to open new ones for whatever comes to your mind.
