### ISSUE TITLE
enter submodule fails

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#18]
I'll admit I wasn't sure what `enter submodule` did and I was trying it out when I got this error: 

```
Welcome to DrRacket, version 7.1 [3m].
Language: racket/gui, with debugging.
> (require (only-in racket/enter dynamic-enter!)
           (only-in syntax/location quote-module-path))
(dynamic-enter! (quote-module-path drracket))
. . ../../Applications/Racket v7.1/collects/racket/private/kw.rkt:1325:47: instantiate: unknown module
  module name: #<resolved-module-path:(submod 'anonymous-module drracket)>
> 
```

newly installed Racket 7.1, & quickscript/-extra

I don't know if it is a bug or if I did something wrong?

S.

**Comment by Metaxal** [comment]
Write the following program in the definitions (untested):

#lang racket

(displayln "This is the main module")

(module+ drracket
  (define foo 'FOO)
  (displayln "This is the drracket submodule"))


Then execute it. Then (in the interactions window) click on Scripts|Enter
submodule|drracket. Press enter and observe the magic. Then you can also
access binding defined in the drracket submodule:
> foo
'FOO

You can also add the drracket submodule to be executed by DrRacket in the
language options (Submodules to Run).

**Comment by spdegabrielle** [comment]
Thanks Laurent
it all works as described. 

Closed with my thanks
