### ISSUE TITLE
Should the 'compile user scripts' menu item run 'reload scripts menu' by default?

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#2]
[Original issue](https://github.com/Metaxal/script-plugin/issues/23) by @spdegabrielle

**Comment by spdegabrielle** [comment]
>Maybe indeed. Or maybe the other way round, or both of them together all the time?

or editing a script should force a recompile?

not a big deal.

**Comment by Metaxal** [comment]
Triggering compilation on save would be nice, even in general for any Racket program, but I don't know if that would be practical. 

I think requesting a reload-menu implies the scripts need to be recompiled in probably all cases.
Since once they are compiled, reloading the menu is no big deal, maybe merging the two makes sense.

**Comment by spdegabrielle** [comment]
+1 for merging the two menu items.

**Comment by Metaxal** [comment]
Done in the latest version, but actually may not be ideal when adding directories of packages where the setup already compiles the scripts.
