### ISSUE TITLE
Can't use #f with #:output-to in define-script

### ISSUE THREAD

**Issue by SFurnace** [Metaxal/quickscript#20]
https://github.com/Metaxal/quickscript/blob/85d50760a0c51303bf9f6b3285a8831112e37fb1/script.rkt#L59

According to the doc of quickscript, `#:output-to` can be `#f`, but it seems this option is missed :-)

**Comment by Metaxal** [comment]
Oops, thanks for spotting this :)
Until I have time to fix it, for now you can make sure the script returns
the value #f, which has the same effect.
