### ISSUE TITLE
remove script from menu in "manage menu"

### ISSUE THREAD

**Issue by mfelleisen** [Metaxal/quickscript#22]
May I suggest a menu functionality for removing unwanted scripts? 

**Rationale** 

Everyone will at first write a script called `foo` that's just doing nonsense. Then this very everyone will discover that it is impossible to remove this script easily. (Well, if you're clever enough to re-open it you will see where it is located in the file system, you can `pushs` there, remove it, reload the menu, and happily go about your work then.) 

I'd submit a patch if I had time.

**Comment by Metaxal** [comment]
Hi Matthias,

Thanks for the report!

You can actually already do this from the script "library": Navigate to
Scripts | Manage scripts | Library.
Then select the folder on the left, and uncheck the unwanted script on the
right side.
Click close and do Scripts | Manage scripts | Reload menu.

The script is gone, but the file still exists (and the script can be
reactivated)

Does this work for you?

**Comment by Metaxal** [comment]
If "Library" is not clear enough, the menu item could be renamed "Organize scripts" or something like that maybe?

**Comment by mfelleisen** [comment]
Ah! 

The word `Library` was totally unintuitive to me, and I didn't even bother to look into it. From whatI can tell this functionality is about managing the visibility (or inclusion) of user scripts. When I see `new` or `open` script, I'd expect to see `delete` or `unload` or both.  For all I know just adding this menu entry and directing it to the same functionality as `Library` may work for people. 

(Speaking of `unload`, what does `unload persistent scripts` do? I selected it and nothing visible happened.)

**Comment by Metaxal** [comment]
`unload persistent scripts` is documented [here](https://docs.racket-lang.org/quickscript/index.html#%28part._.The_script_s_properties%29).

The lack of `delete` and  `unload` is partly for consistency with DrRacket's file menu, which does not have  `delete file` or `unload file`. I'm not fundamentally against them though.

Open is for editing a script (as in `File | Open`). Would `Edit` be better?

**Comment by mfelleisen** [comment]
I figured you based your menu on the DrRacket | File menu. I think this is a serious design mistake.  

- If you wish to have a parallel, you need to ask programmers where to save the script file. Then a `script` becomes just another program that developers manage. And tasking them with removing the files on their own is reasonable. 

- But, I think the analogy between `files` and `scripts` is wrong. The first lives in the file system, and the developer knows where to look and what to look for. The second lives inside the IDE and works across many code repositories. 

So you need to choose one of these two options and stick with it. At the moment, it looks like you mixed them. 

As for the word `edit`, `open` is great. It made total sense to me .. and it would make sense in either design alternative.

**Comment by Metaxal** [comment]
You're right, it's somewhat half of both.

What about a "Disable scripts…" or "Organize scripts…" item that just opens the library?

**Comment by mfelleisen** [comment]
`Disable` is good.

**Comment by Metaxal** [comment]
I've added this item, it will come with the next push (I'm waiting to build some automatic tests).
