### ISSUE TITLE
include quickscripts-extra scripts by default

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#24]
The size of quick scripts-extra is tiny, and I can't see a good reason for not including it in quickscripts by default. I'd use it more if a collection of useful scripts was already in place.  maybe leave novelties and 'script of the day' in '-extra

**Comment by Metaxal** [comment]
I'm not too sure, there are several things to consider:
* since quickscript is now by default in DrRacket, that would require upstream approval,
* quickscript-extra is currently a little messy (with examples, some good scripts and some half-baked ones) so it would require some cleaning beforehand,
* some users may not want these scripts, just quickscript, and no one  wants to have to remove by hand a package that has been installed automatically.
* I think currently there's also a nice separation between the clean-and-simple logic (quickscript) and the messy-and-verbose content (quickscript-extra).

**Comment by spdegabrielle** [comment]
Sorry, I really meant a subset of the items in quickscript-extra - not the demos and examples.

Do you think approval would be hard to get for the following:
- [ ] open-dir: Open the system’s file browser in the current directory.
- [ ] open-terminal: Open a terminal in the current directory (linux only).
- [ ] sort-lines: Sorts the selected lines in (anti-)alphabetical order.
- [ ] def-signatures: Displays the signature of the procedure under the cursor (like DrRacket’s blue box but works also when the file does not compile).
- [ ] author-date: Insert text snippets with author, date, time, and licence.
- [ ] enter-submod: Easily enter a submodule (main, test, drracket, etc.) in the interaction window.
- [ ] extract-function: Extracts a block of code out of its context and generates a function and a call

**Comment by spdegabrielle** [comment]
- since quickscript is now by default in DrRacket, that would require upstream approval,

understood. Migrating a subset of useful scripts, not demos or examples, into Quickscript would be better.

- quickscript-extra is currently a little messy (with examples, some good scripts and some half-baked ones) so it would require some cleaning beforehand,

Agreed - it should stay separate 


- some users may not want these scripts, just quickscript, and no one wants to have to remove by hand a package that has been installed automatically.

agreed for many of the exmples and demos
I think this should be reconsiders for a core of useful scripts. After all emacs doesn't come with nothing installed. (Currently quickscript on its own doesn't do anything and it is not clear to a new user downloading why they should spend their time on it.)

- I think currently there's also a nice separation between the clean-and-simple logic (quickscript) and the messy-and-verbose content (quickscript-extra).

Agreed. Moving a few useful scripts across is a better idea.

s.

**Comment by Metaxal** [comment]
First, we could create a `quickscript-extra-core` package that includes only the most important scripts (regexp-replace and provided-by would be part of them IMO).
Second, Quickscript could include by default a single script that interrogates the (default) catalog to see what quickscript packages exist and propose to install them.
How does that sound? (I'm not committing to anything yet, just thinking)

**Comment by spdegabrielle** [comment]
sounds good!

Can I suggest also a couple of useful scripts could be included in the quickscripts itself.
if not the full list I suggested then maybe just def-signatures, design-recipe, author-date, enter-submod and extract-function?

We can share the workload; :smiley:
- [ ] create the script that interrogates the (default) catal og to see what quickscript packages exist and propose to install them, (@Metaxal )
- [ ] create the quickscript-extra-core package (@Metaxal )
- [ ] migrate scripts from quickscript-extra to quickscript-core via pr (@spdegabrielle )
- [ ] propose key scripts(def-signatures, design-recipe, author-date, enter-submod and extract-function) to be included in quickscript via pr (@spdegabrielle ) 

S.

**Comment by spdegabrielle** [comment]
closing this - so much has changed with with introduction of url2script and command palette that I think the new ticket is better.
