### ISSUE TITLE
Documentation change broke the nightly build

### ISSUE THREAD

**Issue by rfindler** [Metaxal/quickscript#31]
The commit https://github.com/Metaxal/quickscript/commit/8104192789012335bb6622d5d2d2080bde76248d introduced the symbol `⚠` into the scribble and that causes the latex back end to fail which breaks the nightly builds.

You can see the error yourself locally in various ways but probably the simplest is to run `pdflatex --dest x --latex quickscript.scrbl` and then `cd x ; pdflatex quickscript`. (Running `pdflatex --pdf quickscript.scrbl` also shows the error but in a way that's harder to read the output; it may be suitable for travis or the like, however.)

**Comment by Metaxal** [comment]
oh! I haven't even thought about running pdflatex.

what do people use to display a warning or important message?

**Comment by Metaxal** [comment]
I used an image. It's not perfect but it's the easiest. (The pdf output is not great, but many things aren't great in the pdf output, like overlapping margin notes)

Thanks for your help!
