### ISSUE TITLE
Sort scripts in the menu

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#38]
Alphabetically?
submenus last?

**Comment by spdegabrielle** [comment]
Popularity
Use

**Comment by Metaxal** [comment]
I usually like adaptive things, but it can sometimes be adversarial to the user's own adaptive behaviour. A fixed order is easier to remember for 'muscle-memory'. (Also, it doesn't require keeping track of statistics.)

Otherwise, a good adaptive order is "last-used", which also takes care of "frequently used", as scripts that are frequently used will (almost always) be near the top.

**Comment by Metaxal** [comment]
Another idea: When there are too many items at the root of the Scripts menu, create submenus with the starting letter of the scripts (only for the scripts that don't specify the menu-path).

**Comment by spdegabrielle** [comment]
group by collection maybe?
+quickscript-extra
+competiton
+user

**Comment by Metaxal** [comment]
Yes, I intend the scripts of the competition to be in a separate submenu.
'User' is just the root Scripts menu.
Not sure about quickscript-extra, this may lead to too many submenus.

The user can always re-organize (without touching the original scripts) by shadowing the scripts, but I guess I'm the only one who knows about that :D

**Comment by spdegabrielle** [comment]
This has made me think more about when scripts are triggered; I'm starting to think that the fixed menus are perhaps the minority and perhaps context menus (in addition to events) are just as an important way to trigger

**Comment by spdegabrielle** [comment]
Can scripts add to the DrRacket context menu. Can they detect the context?
Can scripts tell if interaction or definitions are currently selected? detect the position? insert at the end of the buffer, or at the beginning? read the buffer?
(sorry so many questions)

**Comment by Metaxal** [comment]
Context menu: Not as of now. Create a new issue if you want.

Definitions or interactions: Yes. You can request the arguments `#:editor ed`, `#:interactions ints`, `#:definitions defs` and if `(eq? ed ints)` then the current editor is the interactions.

The position of the cursor can be retrieved with `(send ed get-start-position)`.
This is used in many scripts in quickscript-extra and elsewhere.
There are many other useful methods for `ed`, in particular you can indeed read the buffer and change it.

**Comment by Metaxal** [comment]
Menu items are now sorted lexicographically, with submenus last. I'm closing this issue. @spdegabrielle if you want some new/different behaviour please open a new issue. Thanks!
