### ISSUE TITLE
readme docs link gives a 404 error

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#4]
http://docs.racket-lang.org/quickscript/index.html

**Comment by Metaxal** [comment]
Thanks, yes, that's kind of on purpose :) It corresponds to the link of the
docs on the pkg.racket-lang.org, when it will be turned into a package.
For now, you can access the docs in the Scripts menu, once installed
(hopefully this one works).

**Comment by Metaxal** [comment]
Now that the package is on the pkg server, the link works, so i'm closing this issue.
