### ISSUE TITLE
BC/CS recompilation does not happen

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#42]
From @bennn:

when I switched from 7.6 BC to 7.6 CS, DrRacket gave this error while loading. Is there a way to avoid it?
```
Error in script file "/Users/ben/Library/Preferences/quickscript/user-scripts/paren-color.rkt":
 read-compiled-linklet: virtual-machine mismatch  expected: "chez-scheme"  found: "racket"  in: /Users/ben/Library/Preferences/quickscript/user-scripts/compiled/paren-color_rkt.zo
```

**Comment by Metaxal** [comment]
@bennn I pushed a fix: 3b97a4cdc952937a1deb11e8548fe5fe748a667d
Previously I wasn't checking the virtual machine, only the version number.

Can you check if you still have an issue? Thanks!

**Comment by bennn** [comment]
Ok, feel free to close this!


I tried testing this with the 7.8 releases, but it's not going well. I was able to (1) run 7.8 BC scripts successfully and (2) reproduce the compile problem on 7.8 CS.

But when I tried updating 7.8 CS quickscript with an `update --clone`, my raco setup started throwing strange errors (below).

I think this means I'm best off using a Racket clone to test, but I can't do that today.

<details>

`raco setup` gives a few errors like this ... one building redex, and others building (and running) DrRacket

```
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: (->* ((object/c-opaque (get-argb-pixels (->* (any/c exact-integer? exact-integer? exact-integer? exact-integer? bytevector?) (boolean? boolean? #:unscaled? boolean?) #<void>)) (get-height (-> any/c exact-integer?)) (get-width (-> any/c exact-integer?)))
  context...:
   not-a-procedure
   proc
   call-in-empty-metacontinuation-frame
   body of "/Applications/RacketCSv7.8/share/pkgs/images-lib/images/private/flomap.rkt"
   temp35_0
   run-module-instance!
   [repeats 1 more time]
   perform-require!
   loop
   [repeats 1 more time]
   finish
   [repeats 19 more times]
   pass-1-and-2-loop
   module-begin-k
   expand-module
   expand-capturing-lifts
```
</details>

**Comment by Metaxal** [comment]
Thanks for trying. The errors look unrelated to quickscript, so that's very strange. I've add issues with --clone too, so the way I usually use the latest github version is by cloning from github directly and renaming the collection to 'quickscript-git', then deactivativing the default quickscript in DrRacket's prefs.

This means that you have two copies of quickscript living at the same time (but only one used by DrRacket), but the worst effect so far is `raco setup` complaining that the docs have duplicate identifiers.

Ideally we should fix the --clone issue but I have no idea where it comes from.

**Comment by bennn** [comment]
I tried a new copy of 7.8 CS. First I tried cloning quickscript and running `raco pkg update --link ./quickscript`. Second I tried removing `share/pkgs/quickscript` and cloning a new copy in its place.

Both times, drracket wouldn't start. I wonder if it was still using an old quickscript somehow?

The first error I got was the old VM error while loading:
![Screen Shot 2020-08-11 at 21 31 07](https://user-images.githubusercontent.com/1731829/89965229-4e59f480-dc1a-11ea-9613-77ea65ae3875.png)

Second, `append` threw an error. No idea if this is related to quickscript:
![Screen Shot 2020-08-11 at 21 31 19](https://user-images.githubusercontent.com/1731829/89965259-603b9780-dc1a-11ea-9a26-6aa7ee3858a2.png)

Next time, I guess I should try making a quickscript-git like you suggest.

**Comment by Metaxal** [comment]
For the first error, my guess is that you have a quickscript that depends on a package that was compiled for BC. Quickscript currently recompiles only the script file, not the dependencies (for a particular reason; I'm working on it, but there's a little [difficulty](https://app.slack.com/client/T06V8J4SU/C06V96CKX/thread/C06V96CKX-1597045988.105900) ). So you may want to `raco setup` your package first, then Quickscript should recompile your scripts modules correctly.

For the second error, it looks like a `message-box%` with a `[style 'ok]` instead of `[style '(ok)]` (I think I fixed something like that some time ago, but I don't recall the details)

**Comment by bennn** [comment]
Ok, I was able to confirm the virtual machine check.
(If I could, I would close this issue now.)

I also learned more about the `append` error. It's from scripts with missing dependencies, because `with-error-message-box` can return `'ok`. I'll open a pull request with more info and a suggestion.

**Comment by Metaxal** [comment]
Fantastic, thanks a ton, Ben!
