### ISSUE TITLE
#:output-to new-tab renders it always in interactions pane of a new tab

### ISSUE THREAD

**Issue by gregid** [Metaxal/quickscript#5]
I tried placing focus in different panes but the result of
```#:output-to new-tab```
is always that the output is generated in the interaction pane of the new-tab. The desired target I believe should depend on current focus. 

In my case I want the script to output it to the definition pane of a new tab (ideally starting from the blank definitions i.e. no ```#lang racket``` at the top).

**Comment by Metaxal** [comment]
Indeed, something is wrong with new-tab. I'll investigate when I'm home.

Thanks for the report!

**Comment by gregid** [comment]
Thanks for looking into it.

One possible enhancement suggestion:
Add new optional property :
```#:new-tab : (or/c dynamic definitions interactions)```
where if ```#:output-to new-tab``` is used then:
dynamic (or focus) - output to depends on current focus
definitions - always output to definitions pane of a new tab
interactions - always output to interactions pane of a new tab

Alternatively allow for something like:
```#:output-to (new-tab definitions)``` to narrow it down with the above mentioned options.

**Comment by Metaxal** [comment]
Hmm, that's strange. On my laptop (running Ubuntu), the current behavior for the script below is to output the text in either the new definitions or the new interactions, depending on which is currently selected (which is what you want I believe).

On another desktop running Debian, it doesn't even create a new tab. (Unfortunately, I can't debug it on this machine.)

What OS and version are you running?

```
#lang racket/base
(require quickscript/script)

(define-script paste-in-new-tab
  #:label "Paste in &new tab"
  #:output-to new-tab
  (λ(selection)
    selection))
```

**Comment by gregid** [comment]
That would be Windows 10

**Comment by Metaxal** [comment]
Ok thanks. The weird behaviour on my desktop is gone after a raco setup and restart, so that's irrelevant now. I think I should be able do something for your problem then.

**Comment by Metaxal** [comment]
Try the latest version. It should output to the definitions by default now, and it should also remove the initial text, e.g. "#lang racket".
(It may take some time to catch up on the pkg server, but I think it's pretty quick usually.)

Tell me if that works for you.

**Comment by gregid** [comment]
Yes, thank you, the update fixed it, although it took me a moment to realise that -> I needed to restart drracket for these changes to take place.

**Comment by Metaxal** [comment]
Great :)
