### ISSUE TITLE
Recompilation still doesn't happen when updating racket...

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#52]

**Comment by Metaxal** [comment]
@rfindler
I think this is mostly fixed, but I still see it happen if a script depends on a package that isn't installed (or hasn't been migrated).

Do you have a suggestion for such cases?

**Comment by Metaxal** [comment]
To confirm: I installed a new snapshot (8.0.0.1), then migrated all my packages, started DrRacket, and no error was reported, as all scripts could be recompiled properly.

**Comment by rfindler** [comment]
I'm seeing that when I have a version 7.9 .zo file in the scripts directory that a git head build will (silently) replace with a newer version .zo file instead of raising an error.

**Comment by Metaxal** [comment]
To make sure I understand correctly:
* by 'that', you mean 'the error'
* the .dep files are also replaced
* the git head make happens while DrRacket 7.9 is running. Afterwards, triggering the script in drr 7.9 or reloading the menu (without quitting drr) raises the error.
Is that correct?

FYI, I've tried recompiling each script before each load, but my tests were hanging for some reason. I'll get back to it soonish.

**Comment by Metaxal** [comment]
I think this is fixed now. I'm closing the issue, feel free to reopen if there are still problems
