### ISSUE TITLE
DrRacket (8.0) crashed, rkt file erased

### ISSUE THREAD

**Issue by AfriPanther** [Metaxal/quickscript#60]
DrRacket crashed in the middle of me coding, then crashed my computer, and upon reboot, my display preferences and languages options were deleted. It was as if I was starting up DrRacket as new. The rkt file I was working on, coincidentally for a homework assignment (rip), is entirely blank. (There are a few thousand characters being interpreted as spaces?). Added a screenshot - I'm not sure how to restore my previous code, but this is clearly appears to be a bug.

![Racket_Crashed](https://user-images.githubusercontent.com/63983255/114957922-95425e80-9e27-11eb-838c-89faea42fe38.png)

**Comment by Metaxal** [comment]
Hi there,

This appears to be a DrRacket-related issue, rather than a Quickscript issue. You'll get better answers if you report it as a [DrRacket issue](https://github.com/racket/drracket/issues).

I'm closing this one, but feel free to re-open it if it turns out to be a Quickscript issue.
