### ISSUE TITLE
Scripts don't show up?

### ISSUE THREAD

**Issue by Metaxal** [Metaxal/quickscript#7]
It was reported twice that scripts don't show up (Windows specific?).
I can't reproduce this behaviour on my machine (Linux), so if anyone has any info about that I'd happily try to fix this.

To enable debugging information, first set the environment variable `PLTSTDERR` to `debug@quickscript` then run `drracket`. On Unix, you can do that in one line on the command line:
`export PLTSTEDDR=debug@quickscript && drracket&`

**Comment by spdegabrielle** [comment]
I'm not getting much out of the debugging. Hopefully I'll get a chance to browse the code to determine why scripts are not being added to the menu.

```
Miriams-MBP:bin spdegabrielle$ export PLTSTEDDR=debug@quickscript && drracket&
[1] 10752
Miriams-MBP:bin spdegabrielle$ objc[10753]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff99570c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x137e65cd8). One of the two will be used. Which one is undefined.
```

**Comment by spdegabrielle** [comment]
worked out this error appears when you load a script

Miriams-MBP:bin spdegabrielle$ export PLTSTEDDR=debug@quickscript && drracket&
[3] 12123
[1]   Done                    export PLTSTEDDR=debug@quickscript && drracket
[2]   Done                    export PLTSTEDDR=debug@quickscript && drracket
Miriams-MBP:bin spdegabrielle$ objc[12124]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff99570c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x132fa5cd8). One of the two will be used. Which one is undefined.

**Comment by Metaxal** [comment]
Hmm, that looks like an OS X specific error then, since no exception is
raised by Racket.

If you could add some `(displayln <current-line>)' here and there in
tool.rkt to see what is loaded, that could help narrowing down the
possibilities.

Thanks for looking into it!

**Comment by Metaxal** [comment]
Just checking if you have any news about this.

**Comment by spdegabrielle** [comment]
Sorry I've been busy lately.

I'll take a look again.

s.

**Comment by Metaxal** [comment]
No worries really, I've been quite busy too :)
Thanks for looking into this!

**Comment by spdegabrielle** [comment]
http://docs.racket-lang.org/reference/runtime.html

**Comment by Metaxal** [comment]
Thanks Stephen, that's a kind of bug that's not easy to track!
