### ISSUE TITLE
enable button in library toggles the script status.

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/quickscript#8]
Pressing  the enable button with an active script selected deactivates a script (removes the tick).

Suggestions: 
* rename the button to 'toggle' or 'toggle status'
* have separate enable and disable buttons

Not a big issue

**Comment by Metaxal** [comment]
Can you give me precise steps to reproduce this? I couldn't reproduce it
myself. Thanks!

**Comment by Metaxal** [comment]
I see an Enable button. Normally it should toggle correctly. At least it does for me. Maybe the behaviour you observe is linked to scripts not appearing in the menu?

![capture du 2018-04-30 09-31-17](https://user-images.githubusercontent.com/1658140/39419833-96650f88-4c59-11e8-96cf-e1f89a1f9a82.png)

**Comment by spdegabrielle** [comment]
![screen shot 2018-05-01 at 21 57 35](https://user-images.githubusercontent.com/108047/39493434-be8ce094-4d8a-11e8-953a-ccd7192f5d22.png)

If you double click the tick box , the button doesn't change state.

In the attached pic, you can see 'reverse.rkt' is already unticked, but the button still shows 'disable'.

**Comment by Metaxal** [comment]
Oh I see, thanks for pointing that out!

I think it should be fixed now. (may take a few minutes to update on the pkg server)

**Comment by spdegabrielle** [comment]
:)
